# Configuration for Dependabot version updates.
# Documentation: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      python:
        patterns:
          - "*"
    ignore:
      # ignore all updates for JAX GPU due to cuda version issue
      - dependency-name: "jax[cuda12_pip]"
