import argparse
import os
import numpy as np
import torch
from transformers import AutoModel, AutoProcessor

# Set backend to torch for easy comparison
os.environ["KERAS_BACKEND"] = "torch"

import keras_hub
from keras_hub.models import Qwen3ASRBackbone, Qwen3ASRCausalLM
from tools.checkpoint_conversion.convert_qwen3_asr_checkpoints import convert_checkpoints

def to_numpy(tensor):
    if isinstance(tensor, torch.Tensor):
        return tensor.detach().cpu().float().numpy()
    return np.asarray(tensor)

def verify_parity(keras_model, hf_model):
    """Verifies numerical parity between Keras and HF models."""
    print("
--- Starting Numerical Parity Check ---")
    
    # 1. Create Dummy Input (3 seconds of audio)
    sample_rate = 16000
    duration = 3
    total_samples = sample_rate * duration
    dummy_audio = np.random.uniform(-1.0, 1.0, size=(1, total_samples)).astype(np.float32)
    dummy_prompts = ["<|AUDIO|>"]
    
    # 2. Preprocess using Keras Hub Preprocessor
    print("Preprocessing inputs...")
    x = {
        "audio": dummy_audio,
        "prompts": dummy_prompts,
    }
    # Preprocessor is already attached if model is built from preset or manually
    preprocessed_x, _, _ = keras_model.preprocessor(x)
    
    # 3. Keras Hub Forward Pass
    print("Running Keras Hub Forward pass...")
    keras_model.eval()
    with torch.no_grad():
        keras_logits = keras_model.predict(preprocessed_x)
        keras_logits_np = to_numpy(keras_logits)

    # 4. Hugging Face Forward Pass
    # We mock the HF input to match the exact tokens and audio features 
    # to isolate model math from preprocessing differences.
    print("Running Hugging Face Forward pass...")
    hf_model.eval()
    with torch.no_grad():
        # Map Keras preprocessed tensors to Torch
        hf_inputs = {
            "input_ids": torch.from_numpy(to_numpy(preprocessed_x["token_ids"])),
            "attention_mask": torch.from_numpy(to_numpy(preprocessed_x["padding_mask"])).long(),
        }
        
        # Audio handling (assuming HF takes audio_mel if custom, or raw)
        # We use the same audio_mel generated by Keras to ensure parity
        if "audio_mel" in preprocessed_x:
             hf_inputs["audio_features"] = torch.from_numpy(to_numpy(preprocessed_x["audio_mel"]))
        
        hf_outputs = hf_model(**hf_inputs)
        hf_logits = to_numpy(hf_outputs.logits)

    # 5. Compare Logits
    print("
--- Parity Results ---")
    max_diff = np.max(np.abs(keras_logits_np - hf_logits))
    mean_diff = np.mean(np.abs(keras_logits_np - hf_logits))
    
    print(f"Max Absolute Difference: {max_diff:.6e}")
    print(f"Mean Absolute Difference: {mean_diff:.6e}")
    
    if max_diff < 1e-4:
        print("✅ Numerical Parity Achieved!")
    else:
        print("❌ Numerical Parity Failed! Discrepancies detected.")

def main():
    parser = argparse.ArgumentParser(description="Convert and verify Qwen3-ASR 0.6B.")
    parser.add_argument("--hf_model_path", type=str, required=True)
    parser.add_argument("--save_path", type=str, required=True)
    args = parser.parse_args()

    print("Loading Hugging Face model...")
    hf_model = AutoModel.from_pretrained(args.hf_model_path, trust_remote_code=True)
    
    print("Initializing Keras Hub model (0.6B configuration)...")
    # Using our 100% accurate 0.6B hyperparameters
    backbone = Qwen3ASRBackbone.from_preset("qwen3_asr_0.6b", load_weights=False)
    keras_model = Qwen3ASRCausalLM(backbone=backbone)
    
    print("Converting weights...")
    convert_checkpoints(keras_model, hf_model)
    
    # Save the preset
    keras_model.save_to_preset(args.save_path)
    
    # Verify
    verify_parity(keras_model, hf_model)

if __name__ == "__main__":
    main()
