"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras_hub.src.models.v2.causal_lm_preprocessor import (
    CausalLMPreprocessor as CausalLMPreprocessor,
)
