"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from keras_hub.src.models.yolo_v8.non_max_suppression import NonMaxSuppression
