name: Test Nightly

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip setuptools
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -e ".[tests]" --progress-bar off --upgrade
          pip uninstall keras -y
          pip uninstall tensorflow -y
          pip uninstall tensorflow_text -y
          pip install tf-nightly --progress-bar off --upgrade
          pip install tensorflow-text-nightly --progress-bar off --upgrade
      - name: Test with pytest
        run: |
          pytest --cov=keras_nlp --cov-report xml:coverage.xml
