name: Test Nightly

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        # TODO: we probably want 3.8 here, but are facing an issue with core
        # keras.
        with:
          python-version: 3.9
      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip setuptools
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements-nightly.txt --progress-bar off
          # --no-deps so pip will not try to install tf and tf-text stable
          # versions after installing the nightly versions above.
          pip install --no-deps -e "." --progress-bar off
      - name: Test with pytest
        run: |
          pytest --cov=keras_nlp --cov-report xml:coverage.xml
      - name: Run integration tests
        run: |
          python pip_build.py --install && cd integration_tests && pytest .
