name: Publish to PyPI

on: push
jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.KERAS_CORE }}"
    - name: Install dependencies
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    - name: Install dependencies
      run: |
          pip install tensorflow==2.12.0
          pip install torch>=2.0.1+cpu
          pip install "jax[cpu]"
          pip install -r requirements.txt --progress-bar off
          cd ..
          git clone git@github.com:keras-team/keras-core.git
          pip install -r keras-core/requirements.txt --progress-bar off
          python keras-core/pip_build.py --install
          cd keras-nlp
    - name: Build a binary wheel and a source tarball
      run: >-
        python pip_build.py
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
