name: Publish to PyPI

on: push
jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Install dependencies
      run: |
        pip install -r requirements.txt --progress-bar off
    - name: Build a binary wheel and a source tarball
      run: >-
        python pip_build.py
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
