name: Remove GPU Test Label
on:
  pull_request_target:
    types: [labeled]

permissions:
  pull-requests: write

jobs:
  remove-label:
    if: github.event.label.name == 'kokoro:force-run'
    runs-on: ubuntu-latest
    steps:
      - name: Remove force-run label
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'kokoro:force-run'
              })
            } catch (error) {
              console.log(`Error removing label: ${error}`)
            }
